&НаСервере
Процедура Тест1()

    ЗаписьЖурналаРегистрации("Событие");// ошибка
    ЗаписьЖурналаРегистрации("Событие", УровеньЖурналаРегистрации.Ошибка);// ошибка
    ЗаписьЖурналаРегистрации("Событие", УровеньЖурналаРегистрации.Ошибка, , );// ошибка

    ЗаписьЖурналаРегистрации("Событие",
      , // ошибка
      , , ПодробноеПредставлениеОшибки(ИнформацияОбОшибке()));

    ЗаписьЖурналаРегистрации("Событие", УровеньЖурналаРегистрации.Ошибка, , , );// ошибка

    Попытка
      ПравильноеИсключениеВКодеСервер();
    Исключение
      ЗаписьЖурналаРегистрации("Событие", УровеньЖурналаРегистрации.Ошибка, , ,
        ОписаниеОшибки()); // ошибка
    КонецПопытки;

    Попытка
      ПравильноеИсключениеВКодеСервер();
    Исключение
      ЗаписьЖурналаРегистрации("Событие", УровеньЖурналаРегистрации.Ошибка, , ,
        "Комментарий 1"); // ошибка
    КонецПопытки;

    Попытка
      ПравильноеИсключениеВКодеСервер();
    Исключение
      ТекстОшибки = "Описание";
      ЗаписьЖурналаРегистрации("Событие", УровеньЖурналаРегистрации.Ошибка, , ,
        "Еще текст " + ТекстОшибки); // ошибка
    КонецПопытки;

    Попытка
      ПравильноеИсключениеВКодеСервер();
    Исключение
      ЗаписьЖурналаРегистрации("Событие", УровеньЖурналаРегистрации.Ошибка, , ,
        "Еще текст " + НетПрисвоения); // ошибка
    КонецПопытки;

    Попытка
      ПравильноеИсключениеВКодеСервер();
    Исключение
      ЗаписьЖурналаРегистрации("Событие", УровеньЖурналаРегистрации.Предупреждение, , , // ошибка
        "Еще текст ");
    КонецПопытки;

    Попытка
      ПравильноеИсключениеВКодеСервер();
    Исключение
      ЗаписьЖурналаРегистрации("Событие", УровеньЖР, , ,
        ПодробноеПредставлениеОшибки(ИнформацияОбОшибке()));
    КонецПопытки;

    Попытка
      ПравильноеИсключениеВКодеСервер();
    Исключение // не проверяем
    КонецПопытки;
КонецПроцедуры

&НаКлиенте
Процедура НеверноеИсключениеВКодеКлиент()
  Попытка
      Тест1();
  Исключение
      ПоказатьПредупреждение(,НСтр("ru = 'Операция не может быть выполнена.'")); // ошибка
  КонецПопытки;
КонецПроцедуры

&НаСервере
Процедура РазрешенныеВызовы()

  ЗаписьЖурналаРегистрации("Событие",
    УровеньЖурналаРегистрации.Ошибка, , ,
    ПодробноеПредставлениеОшибки(ИнформацияОбОшибке()));

  ЗаписьЖурналаРегистрации(НСтр("ru = 'Мой механизм.Действие с возможной ошибкой'", КодОсновногоЯзыка),
    УровеньЖурналаРегистрации.Ошибка, , ,
    НСтр("ru = 'Во время выполнения действия произошла неизвестная ошибка.'") + Символы.ПС +
    ПодробноеПредставлениеОшибки(ИнформацияОбОшибке()));

    Попытка
      ПравильноеИсключениеВКодеСервер();
    Исключение
      ВызватьИсключение;
    КонецПопытки;

    Попытка
      ПравильноеИсключениеВКодеСервер();
    Исключение
      ЗаписьЖурналаРегистрации("Событие",
        УровеньЖурналаРегистрации.Ошибка, , ,
        ОписаниеОшибки());

      ВызватьИсключение;
    КонецПопытки;

    Попытка
      ПравильноеИсключениеВКодеСервер();
    Исключение

      ТекстОшибки = ПодробноеПредставлениеОшибки(ИнформацияОбОшибке());
      ЗаписьЖурналаРегистрации("Событие", УровеньЖурналаРегистрации.Ошибка, , ,
         ТекстОшибки);
    КонецПопытки;

    ЗаписьЖурналаРегистрации("Событие",
                УровеньЖурналаРегистрации.Ошибка, , ,
                "ТекстОшибки"); // нет ошибки, т.к. блок вне Попытки

    ТекстОшибки = "Текст";
    ЗаписьЖурналаРегистрации("Событие",
                УровеньЖурналаРегистрации.Ошибка, , ,
                ТекстОшибки); // нет ошибки, т.к. блок вне Попытки

КонецПроцедуры

&НаКлиенте
Процедура ПравильноеИсключениеВКодеКлиент()
  Попытка
    ИсключениеВКодеСервер();
  Исключение
      ТекстСообщения = КраткоеПредставлениеОшибки(ИнформацияОбОшибке());
      ПоказатьПредупреждение(,НСтр("ru = 'Операция не может быть выполнена по причине:'") + Символы.ПС + ТекстСообщения);
  КонецПопытки;
КонецПроцедуры

&НаСервере
Процедура ПравильноеИсключениеВКодеСервер()
  Попытка
    // код, приводящий к вызову исключения
    А = 10;
  Исключение
    // Запись события в журнал регистрации для системного администратора.
    ЗаписьЖурналаРегистрации(НСтр("ru = 'Выполнение операции'"),
       УровеньЖурналаРегистрации.Ошибка,,,
       ПодробноеПредставлениеОшибки(ИнформацияОбОшибке()));
    ВызватьИсключение;
  КонецПопытки;
КонецПроцедуры

&НаКлиенте
Процедура ПравильноСоздатьФайлНаДиске()
  Попытка
      // клиентский код, приводящий к вызову исключения
      СоздатьФайлНаДиске();
  Исключение
      ТекстСообщения = КраткоеПредставлениеОшибки(ИнформацияОбОшибке());
      ПоказатьПредупреждение(,НСтр("ru = 'Операция не может быть выполнена по причине:'") + Символы.ПС + ТекстСообщения);
      ЗаписатьОшибкуРаботыСФайлами(ПодробноеПредставлениеОшибки(ИнформацияОбОшибке()));
  КонецПопытки;
КонецПроцедуры

&НаСервереБезКонтекста
Процедура ПравильноЗаписатьОшибкуРаботыСФайлами(Знач ПодробноеПредставлениеОшибки)
    ЗаписьЖурналаРегистрации(НСтр("ru = 'Выполнение операции'"),
       УровеньЖурналаРегистрации.Ошибка,,,
       ПодробноеПредставлениеОшибки);
КонецПроцедуры

&НаСервере
Процедура ПеременнаяОпределенаВБлокеВыше()
  ТекстОшибки = "";
  Попытка
    // код, приводящий к вызову исключения
    А = 10;
  Исключение
    // Запись события в журнал регистрации для системного администратора.
    ЗаписьЖурналаРегистрации(НСтр("ru = 'Выполнение операции'"),
       УровеньЖурналаРегистрации.Ошибка,,,
       ТекстОшибки);
  КонецПопытки;
КонецПроцедуры
